name: Test build

on:
  push:
  pull_request:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Ensure build was committed (necessary for Github Actions)
        run: "[[ -z $(git status -s dist ':^dist/src') ]]"

      - name: "[Test] Unit tests"
        run: yarn test
